---
# Gather date time data
- name: Gather facts to determine date
  setup:
    gather_subset:
      - '!all'
      - '!any'
      - date_time
  tags:
    - always

# Convert list of clients to comma-separated string
- name: Create a comma-separated list of clients
  set_fact:
        gluster_clients: "{{ glusterfs_perf_clients|join(',') }}"

# tasks file for glusterfs-perf
- name: Pre-requisites for setting up Gluster HCI
  import_tasks: prereq.yml
  tags:
    - prereq

# Setup GlusterFS cluster
- name: Setup GlusterFS cluster
  import_tasks: glustervol.yml
  tags:
    - clustersetup

# Run the smallfile performance tool on the cluster
- name: Run smallfile perf tool
  import_tasks: smallfile/smallfile-perf.yml
  tags:
    - runperf

# These tests are failing to execute due to some setup issues.
# Please check and uncomment once fixed and tested.
# # Run the fio performance tool on the cluster
# - name: Run fio tests
#   import_tasks: fio/fio-perf.yml
#   tags:
#     - runperf, fio

# # Run the pgbench performance tool on the cluster
# - name: Run pgbench tests
#   import_tasks: pgbench/pgbench-run.yml
#   tags:
#     - runperf, pgbench

# # Run the untar and rm -rf test
# - name: Run untar and rm -rf test
#   import_tasks: untar/untar-run.yml
#   tags:
#     - runperf, untar

# Send mail attaching the results
- name: Send mail attaching the results
  import_tasks: sendmail.yml
  when: glusterfs_perf_to_list is defined
  tags:
    - mail
